---
- name: Download Jenkins SSH key
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Add Jenkins to Apt repositories
  shell: echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list

- name: Update apt package cache
  action: apt update_cache=yes

- name: Install Jenkins
  apt: pkg={{ item }} state=latest
  with_items:
    - jenkins

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Wait for Jenkins to start up before proceeding.
  shell: curl --head --silent http://{{ jenkins.hostname }}:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: "{{ jenkins.connection_retries }}"
  delay: "{{ jenkins.connection_delay }}"
  changed_when: false

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins.hostname }}:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins.cli_dest }}"

- include: plugins.yml
